package univers;

public enum Lieux {
    PLANQUE_QUARTIER_MALFAME,
    HOTEL_PRES_DU_PORT,
    RUELLE_SOMBRE_CENTRE_VILLE,
    LIEU_MYSTERE_MESSAGE_CRYPTE,
    ENTREPOT,
    SUITE,
    APPARTEMENT,
    LIEU_INCONNU
}
